[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    me-no-dev/AsyncTCP @ ^1.1.1
    bblanchon/ArduinoJson @ ^7.0.0

board_build.partitions = min_spiffs.csv

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DMAX_LEDS=144
    -DMAX_SLICES=720

[env:native]
platform = native
test_build_src = true
build_src_filter = -<*> +<framebuffer.cpp> +<patterns/*.cpp>
build_flags =
    -DMAX_LEDS=144
    -DMAX_SLICES=720
    -Itest/stubs
